[2025-09-11 06:16:25,474] ERROR in app: Exception on /api/produtos/1 [DELETE]
Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: movimentacoes.produto_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/decorators.py", line 13, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/routes/produtos.py", line 117, in delete_produto
    db.session.commit()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: movimentacoes.produto_id
[SQL: UPDATE movimentacoes SET produto_id=? WHERE movimentacoes.id = ?]
[parameters: (None, 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2025-09-11 06:16:31,460] ERROR in app: Exception on /api/setores/1 [DELETE]
Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: movimentacoes.setor_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/decorators.py", line 13, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/routes/setores.py", line 87, in delete_setor
    db.session.commit()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: movimentacoes.setor_id
[SQL: UPDATE movimentacoes SET setor_id=? WHERE movimentacoes.id = ?]
[parameters: (None, 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[2025-09-11 06:16:36,970] ERROR in app: Exception on /api/almoxarifados/1 [DELETE]
Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: produtos.almoxarifado_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/decorators.py", line 13, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/f6p.gmapsistemas.com.br/app/routes/almoxarifados.py", line 75, in delete_almoxarifado
    db.session.commit()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1415, in execute
    return meth(
           ^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/sql/elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/gmapsist/virtualenv/f6p.gmapsistemas.com.br/3.12/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: produtos.almoxarifado_id
[SQL: UPDATE produtos SET almoxarifado_id=? WHERE produtos.id = ?]
[parameters: (None, 1)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[UID:4071][22484] Child process with pid: 1762 was killed by signal: 15, core dumped: no
